server.port=${CONFIG_SERVICE_PORT}
spring.application.name=config
spring.cloud.config.server.git.uri=${CONFIG_SERVICE_URL}

spring.cloud.config.server.git.default-label=master

spring.cloud.config.server.git.search-paths=${CONFIG_SERVICE_DIR}
